### ISSUE TITLE
Front-end navigation?

### ISSUE THREAD

**Issue by giekaton** [inertiajs/inertia#320]
I have my views logic defined in my Vue app.

When I navigate to e.g. `/shopping-cart`, I do not need to call the backend since the layout is rendered from the frontend.

So, if I use `<inertia-link href="/shopping-cart">Shopping Cart</inertia>`, I get the desired effect, but Inertia makes the backend call, which is not necessary, and the page change takes around 1 second, while it should be instant.

If I navigate using Vue, e.g. `this.view = "ShoppingCart"`, the view is rendered instantly, but the page URL doesn't update, and the back and forward buttons are not working.

What I need, is a similar functionality like Vue Router. Since this is a common functionality for SPAs, I think that this should be possible with Inertia or vanilla JS.

I also need my links in HTML to be rendered as traditional `<a href="/shopping-cart">`.

A workaround is to create a normal <a> link with the desired url, and add onclick listener, like this: `<a href="/shopping-cart" onclick="inertiaOpenPage('pageName'); return true;">`

And then in the `inertiaOpenPage` function, I would put:
```
inertiaOpenPage(pageName) {
  this.view = pageName;
  this.$inertia.visit(pageName, {
    method: 'get',
    replace: false,
    preserveState: true,
    preserveScroll: true,
  })
}
```

This works. It changes the view instantly and changes the URL with both back and forward buttons working, but still, this makes the unnecessary backend call and wastes server/traffic resources.

Any other ideas or suggestions?

**Comment by giekaton** [comment]
I have installed vue-router alongside Inertia. It works well and solves my issue.

I wonder if this is somehow a bad practice since it's everywhere noted that Inertia should be used without the vue-router.

While it works well, when navigating back with the button, the following error appears in the console. Any ideas how to fix this? I guess there might be a conflict between Inertia and vue-router.

```
app.js:52166 Uncaught Error: Cannot find module './undefined'
    at webpackContextResolve (app.js:52166)
    at webpackContext (app.js:52161)
    at Object.resolveComponent (app.js:52997)
    at Object.setPage (app.js:109)
    at Object.restoreState (app.js:109)
```

**Comment by reinink** [comment]
This is something we're considering for the future. See #261

I've never used Vue Router alongside Inertia, but I suspect that wouldn't work well, since Inertia picks up all history popstate events...which would include the Vue Router visits.
